name: Auto Release

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/workflows/auto-release.yml'

jobs:
  auto-release:
    # Skip if commit message contains [skip actions]
    if: "!contains(github.event.head_commit.message, '[skip actions]')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build action
        run: |
          echo "🔨 Building action..."
          bun run build
          
          # CRITICAL: Verify build output
          if [ ! -f "dist/index.js" ]; then
            echo "❌ BUILD FAILED: dist/index.js not found!"
            exit 1
          fi
          
          FILE_SIZE=$(stat -f%z dist/index.js 2>/dev/null || stat -c%s dist/index.js 2>/dev/null || echo "0")
          if [ "$FILE_SIZE" -lt 1000000 ]; then
            echo "❌ BUILD FAILED: dist/index.js is too small ($FILE_SIZE bytes)!"
            exit 1
          fi
          
          echo "✅ Build successful - dist/index.js created ($FILE_SIZE bytes)"

      - name: Get current version
        id: current-version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Bump patch version
        id: new-version
        run: |
          CURRENT_VERSION="${{ steps.current-version.outputs.current_version }}"
          
          # Split version into components
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          
          # Bump patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag_version=v$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Bumped version from $CURRENT_VERSION to $NEW_VERSION"

      - name: Update package.json version
        run: |
          NEW_VERSION="${{ steps.new-version.outputs.new_version }}"
          npm version $NEW_VERSION --no-git-tag-version
          echo "Updated package.json to version $NEW_VERSION"

      - name: Commit version bump and build
        run: |
          NEW_VERSION="${{ steps.new-version.outputs.new_version }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # CRITICAL: Always include built files in the commit
          git add package.json
          git add dist/
          
          # Verify that dist/index.js exists before committing
          if [ ! -f "dist/index.js" ]; then
            echo "❌ ERROR: dist/index.js not found! Build failed!"
            exit 1
          fi
          
          # Check file size to ensure it's properly built
          FILE_SIZE=$(stat -f%z dist/index.js 2>/dev/null || stat -c%s dist/index.js 2>/dev/null || echo "0")
          if [ "$FILE_SIZE" -lt 1000000 ]; then
            echo "❌ ERROR: dist/index.js is too small ($FILE_SIZE bytes). Build may have failed!"
            exit 1
          fi
          
          echo "✅ dist/index.js exists and is properly sized ($FILE_SIZE bytes)"
          git commit -m "chore: bump version to $NEW_VERSION and build [skip actions]"
          git push origin main

      - name: Create and push tag
        run: |
          TAG_VERSION="${{ steps.new-version.outputs.tag_version }}"
          NEW_VERSION="${{ steps.new-version.outputs.new_version }}"
          
          # Check if tag already exists
          if git tag -l | grep -q "^$TAG_VERSION$"; then
            echo "Tag $TAG_VERSION already exists, skipping tag creation"
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            git tag -a $TAG_VERSION -m "Release $TAG_VERSION"
            git push origin $TAG_VERSION
            echo "Created and pushed tag: $TAG_VERSION"
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi
          
          # CRITICAL: Verify that the tag contains the built files
          echo "🔍 Verifying tag contains built files..."
          git checkout $TAG_VERSION
          if [ ! -f "dist/index.js" ]; then
            echo "❌ CRITICAL ERROR: Tag $TAG_VERSION does not contain dist/index.js!"
            echo "❌ This will cause 'File not found' errors in CI/CD pipelines!"
            exit 1
          fi
          
          FILE_SIZE=$(stat -f%z dist/index.js 2>/dev/null || stat -c%s dist/index.js 2>/dev/null || echo "0")
          if [ "$FILE_SIZE" -lt 1000000 ]; then
            echo "❌ CRITICAL ERROR: Tag $TAG_VERSION contains invalid dist/index.js ($FILE_SIZE bytes)!"
            exit 1
          fi
          
          echo "✅ Tag $TAG_VERSION verified - contains valid dist/index.js ($FILE_SIZE bytes)"
          git checkout main

      - name: Update latest tag
        run: |
          TAG_VERSION="${{ steps.new-version.outputs.tag_version }}"
          git tag -f latest $TAG_VERSION
          git push origin latest --force
          echo "Updated latest tag to point to $TAG_VERSION"
          
          # CRITICAL: Final verification that latest tag contains built files
          echo "🔍 Final verification of latest tag..."
          git checkout latest
          if [ ! -f "dist/index.js" ]; then
            echo "❌ CRITICAL ERROR: Latest tag does not contain dist/index.js!"
            echo "❌ This will break all CI/CD pipelines using @latest!"
            exit 1
          fi
          
          FILE_SIZE=$(stat -f%z dist/index.js 2>/dev/null || stat -c%s dist/index.js 2>/dev/null || echo "0")
          echo "✅ Latest tag verified - contains dist/index.js ($FILE_SIZE bytes)"
          git checkout main

      - name: Create GitHub release
        run: |
          TAG_VERSION="${{ steps.new-version.outputs.tag_version }}"
          NEW_VERSION="${{ steps.new-version.outputs.new_version }}"
          
          # Check if release already exists
          if gh release view $TAG_VERSION >/dev/null 2>&1; then
            echo "Release $TAG_VERSION already exists, skipping release creation"
          else
            # Generate release notes
            RELEASE_NOTES="## What's Changed\n\n- Automated release for version $NEW_VERSION\n- Discord Pipeline Tracker GitHub Action\n- Real-time CI/CD pipeline tracking in Discord\n- Support for pipeline initialization, step updates, completion, and failure handling\n\n## Version\n- **Version:** $NEW_VERSION\n- **Tag:** $TAG_VERSION\n\n## Usage\n\n\`\`\`yaml\n- uses: flazouh/discord-tracker@$TAG_VERSION\n  with:\n    action: 'init'\n    pr_number: \${{ github.event.number }}\n    discord_bot_token: \${{ secrets.DISCORD_BOT_TOKEN }}\n    discord_channel_id: \${{ secrets.DISCORD_CHANNEL_ID }}\n\`\`\`"
            
            # Create release
            gh release create $TAG_VERSION \
              --title "Release $TAG_VERSION" \
              --notes "$RELEASE_NOTES" \
              --target main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify completion
        run: |
          TAG_VERSION="${{ steps.new-version.outputs.tag_version }}"
          NEW_VERSION="${{ steps.new-version.outputs.new_version }}"
          echo "🎉 Successfully created release $TAG_VERSION!"
          echo "📦 Version: $NEW_VERSION"
          echo "🏷️  Tag: $TAG_VERSION"
          echo "📝 Release notes generated automatically" 