name: Auto Release

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.github/workflows/auto-release.yml'

jobs:
  auto-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get current version
        id: current-version
        run: |
          CURRENT_VERSION=$(grep '^version = ' Cargo.toml | cut -d'"' -f2)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Bump patch version
        id: new-version
        run: |
          CURRENT_VERSION="${{ steps.current-version.outputs.current_version }}"
          
          # Split version into components
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          
          # Bump patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "tag_version=v$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Bumped version from $CURRENT_VERSION to $NEW_VERSION"

      - name: Update Cargo.toml version
        run: |
          NEW_VERSION="${{ steps.new-version.outputs.new_version }}"
          sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" Cargo.toml
          echo "Updated Cargo.toml to version $NEW_VERSION"

      - name: Commit version bump
        run: |
          NEW_VERSION="${{ steps.new-version.outputs.new_version }}"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Cargo.toml
          git commit -m "chore: bump version to $NEW_VERSION [skip ci]"
          git push origin main

      - name: Create and push tag
        run: |
          TAG_VERSION="${{ steps.new-version.outputs.tag_version }}"
          NEW_VERSION="${{ steps.new-version.outputs.new_version }}"
          
          git tag -a $TAG_VERSION -m "Release $TAG_VERSION"
          git push origin $TAG_VERSION
          echo "Created and pushed tag: $TAG_VERSION"

      - name: Update latest tag
        run: |
          TAG_VERSION="${{ steps.new-version.outputs.tag_version }}"
          git tag -f latest $TAG_VERSION
          git push origin latest --force
          echo "Updated latest tag to point to $TAG_VERSION"

      - name: Create GitHub release
        run: |
          TAG_VERSION="${{ steps.new-version.outputs.tag_version }}"
          NEW_VERSION="${{ steps.new-version.outputs.new_version }}"
          
          # Generate release notes
          RELEASE_NOTES="## What's Changed\n\n- Automated release for version $NEW_VERSION\n- Production deployment improvements\n- Docker and GitHub Action optimizations\n\n## Version\n- **Version:** $NEW_VERSION\n- **Tag:** $TAG_VERSION\n\n## Usage\n\n\`\`\`yaml\n- uses: flazouh/discord-tracker@$TAG_VERSION\n\`\`\`"
          
          # Create release
          gh release create $TAG_VERSION \
            --title "Release $TAG_VERSION" \
            --notes "$RELEASE_NOTES" \
            --target main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify completion
        run: |
          TAG_VERSION="${{ steps.new-version.outputs.tag_version }}"
          NEW_VERSION="${{ steps.new-version.outputs.new_version }}"
          echo "🎉 Successfully created release $TAG_VERSION!"
          echo "📦 Version: $NEW_VERSION"
          echo "🏷️  Tag: $TAG_VERSION"
          echo "📝 Release notes generated automatically" 