name: Download Discord Tracker Binary

on:
  workflow_call:
    inputs:
      version:
        description: 'Version of discord-tracker to download'
        required: false
        default: 'v0.2.1'
        type: string
      platform:
        description: 'Platform to download (linux-x64, windows-x64, macos-x64)'
        required: false
        default: 'linux-x64'
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    outputs:
      binary-path: ${{ steps.download.outputs.path }}
    steps:
      - name: Download Discord Tracker Binary
        id: download
        run: |
          VERSION="${{ inputs.version }}"
          PLATFORM="${{ inputs.platform }}"
          
          if [ "$PLATFORM" = "windows-x64" ]; then
            BINARY_NAME="discord-tracker-windows-x64.exe"
          else
            BINARY_NAME="discord-tracker-$PLATFORM"
          fi
          
          echo "Downloading discord-tracker $VERSION for $PLATFORM..."
          curl -L -o discord-tracker "https://github.com/flazouh/discord-tracker/releases/download/$VERSION/$BINARY_NAME"
          chmod +x discord-tracker
          
          echo "path=$(pwd)/discord-tracker" >> $GITHUB_OUTPUT
          echo "Binary downloaded successfully: $(pwd)/discord-tracker" 