name: Integration Tests

on:
  push:
    branches: [main, v1]
  pull_request:
    branches: [main, v1]
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build action
        run: bun run build

      - name: Test action initialization
        uses: ./
        with:
          action: 'init'
          pr_number: '999'
          pr_title: 'Integration Test PR'
          author: 'integration-test'
          repository: 'flazouh/discord-tracker'
          branch: 'integration-test'
          discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}
          discord_channel_id: ${{ secrets.DISCORD_CHANNEL_ID }}
        env:
          ACTIONS_STEP_DEBUG: true
        continue-on-error: true

      - name: Test step update
        uses: ./
        with:
          action: 'step'
          step_number: '1'
          total_steps: '3'
          step_name: 'Integration Test Step'
          status: 'success'
          additional_info: '{"test": "integration", "duration": "5s", "coverage": "100%"}'
          discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}
          discord_channel_id: ${{ secrets.DISCORD_CHANNEL_ID }}
        env:
          ACTIONS_STEP_DEBUG: true
        continue-on-error: true

      - name: Test step failure
        uses: ./
        with:
          action: 'step'
          step_number: '2'
          total_steps: '3'
          step_name: 'Failed Test Step'
          status: 'failed'
          additional_info: '{"error": "Simulated failure for testing"}'
          discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}
          discord_channel_id: ${{ secrets.DISCORD_CHANNEL_ID }}
        env:
          ACTIONS_STEP_DEBUG: true
        continue-on-error: true

      - name: Test completion
        uses: ./
        with:
          action: 'complete'
          discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}
          discord_channel_id: ${{ secrets.DISCORD_CHANNEL_ID }}
        env:
          ACTIONS_STEP_DEBUG: true
        continue-on-error: true

      - name: Test failure handling
        uses: ./
        with:
          action: 'fail'
          step_name: 'Integration Test'
          error_message: 'Integration test completed - this is expected'
          discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}
          discord_channel_id: ${{ secrets.DISCORD_CHANNEL_ID }}
        env:
          ACTIONS_STEP_DEBUG: true
        continue-on-error: true

      - name: Report test results
        run: |
          echo "🎉 Integration tests completed!"
          echo "📝 Check Discord channel for test messages"
          echo "✅ All tests ran (some may have failed due to missing Discord credentials)"
          echo "🔧 To run with real Discord credentials, add DISCORD_BOT_TOKEN and DISCORD_CHANNEL_ID secrets" 